Repository GDRCD/GDRCD, pull requests merged in 2021-12, with the labels that each got.

#231 [hotfix] GDRCD 5.6.0.1 - Implementato AudioController per la gestione notifiche
  config.inc.php
  includes/AudioController.php
  includes/required.php
  pages/frame/messages/index.inc.php
  pages/frame_chat.inc.php
  ref_header.inc.php
Labels: enhancement, v5.6.0.1

#223 [master] GDRCD - 5.6.0.1
  ISTRUZIONI.txt
  README.md
  config.inc.php
  db_versions/2020072500_GDRCD551.php
  db_versions/2021103018_GDRCD56.php
  db_versions/2021103019_GDRCD5601.php
  header.inc.php
  includes/AudioController.php
  includes/required.php
  license.md
  pages/frame/messages/index.inc.php
  pages/frame_chat.inc.php
  pages/homepage/home.inc.php
  pages/scheda/menu.inc.php
  pages/scheda/roles/index.inc.php
  pages/scheda/roles/search.inc.php
  ref_header.inc.php
  vocabulary/COME-FARE-LA-LAND---LEGGIMI!.md
Labels: pending, fix, v5.6.0.1

#232 Oggetti
  classes/Controller/Chat.class.php
  classes/Controller/Mercato.class.php
  classes/Controller/Oggetti.class.php
  classes/Controller/Personaggio.class.php
  classes/Controller/Scheda/Scheda.class.php
  classes/Controller/Scheda/SchedaOggetti.class.php
  classes/Libraries/Filters.class.php
  classes/Libraries/Menu.class.php
  config.inc.php
  gdrcd_db.sql
  pages/gestione/manutenzione/deleted.inc.php
  pages/gestione/manutenzione/missing.inc.php
  pages/gestione/mercato/gestione_mercato_ajax.php
  pages/gestione/mercato/gestione_mercato_negozi.js
  pages/gestione/mercato/gestione_mercato_negozi.php
  pages/gestione/mercato/gestione_mercato_oggetti.php
  pages/gestione/oggetti/gestione_oggetti.js
  pages/gestione/oggetti/gestione_oggetti.php
  pages/gestione/oggetti/gestione_oggetti_ajax.php
  pages/gestione/oggetti/gestione_oggetti_posizioni.js
  pages/gestione/oggetti/gestione_oggetti_posizioni.php
  pages/gestione/oggetti/gestione_oggetti_tipo.js
  pages/gestione/oggetti/gestione_oggetti_tipo.php
  pages/gestione/pagina_gestione_example.php
  pages/gestione_mercato.inc.php
  pages/gestione_mercato_negozi.inc.php
  pages/gestione_mercato_oggetti.inc.php
  pages/gestione_oggetti.inc.php
  pages/gestione_oggetti_posizioni.inc.php
  pages/gestione_oggetti_tipo.inc.php
  pages/scheda.inc.php
  pages/scheda/menu.inc.php
  pages/scheda/oggetti/scheda_oggetti.php
  pages/scheda_equip.inc.php
  pages/scheda_oggetti.inc.php
  pages/servizi/mercato/mercato_index.php
  pages/servizi/mercato/mercato_objects.php
  pages/servizi/mercato/mercato_shops.php
  pages/servizi_mercato.inc.php
  pages/user_cambio_nome.inc.php
  themes/advanced/imgs/body/head.png
  themes/advanced/imgs/body/torax.png
  themes/advanced/imgs/items/scopa.png
  themes/advanced/imgs/shops/armeria.jpg
  themes/advanced/main.css
  themes/advanced/scheda.css
Labels: enhancement, v6.0
