Repository GDRCD/GDRCD, pull requests merged in 2021-11, with the labels that each got.

#200 GDRCD - Gestione migliorata quest
  classes/Controller/Gestione.class.php
  classes/Controller/Personaggio.class.php
  classes/Controller/Quest.class.php
  classes/Libraries/DB.class.php
  classes/Libraries/Filters.class.php
  classes/Libraries/Functions.class.php
  config.inc.php
  core/constant_values.php
  gdrcd_db.sql
  header.inc.php
  pages/gestione/abilita/Extra/gestione_abilita_box.php
  pages/gestione/abilita/Requisiti/gestione_requisiti.php
  pages/gestione/costanti/gestione_costanti_box.js
  pages/gestione/costanti/gestione_costanti_box.php
  pages/gestione/quest/JS/gestione_quest_edit.js
  pages/gestione/quest/JS/gestione_quest_insert.js
  pages/gestione/quest/gestione_quest_ajax.php
  pages/gestione/quest/gestione_quest_delete.php
  pages/gestione/quest/gestione_quest_edit.php
  pages/gestione/quest/gestione_quest_index.php
  pages/gestione/quest/gestione_quest_insert.php
  pages/gestione/quest/gestione_quest_list.php
  pages/gestione/trame/gestione_trame_delete.php
  pages/gestione/trame/gestione_trame_edit.php
  pages/gestione/trame/gestione_trame_index.php
  pages/gestione/trame/gestione_trame_insert.php
  pages/gestione/trame/gestione_trame_list.php
  pages/gestione_quest.inc.php
  pages/gestione_trame.inc.php
  pages/link_menu.inc.php
  pages/scheda_px.inc.php
  pages/servizi/anagrafe/index.inc.php
  plugins/Ajax.js
  themes/advanced/main.css
  themes/advanced/scheda.css
Labels: enhancement, pending

#221 Db migrations dev
  classes/Libraries/Base.class.php
  classes/Libraries/DbMigration.class.php
  classes/Libraries/DbMigrationEngine.class.php
  db_versions/2020072500_GDRCD551.php
  db_versions/2021103018_GDRCD56.php
  db_versions/2021110101_DiarioPg.php
  db_versions/2021110102_DefaultLengths.php
  db_versions/2021110103_AddStoria.php
  db_versions/2021110104_ImprovedAbilities.php
  db_versions/2021110105_ObjectsKey.php
  db_versions/2021110106_ConfigTable.php
  db_versions/2021110107_Permissions.php
  db_versions/2021110108_AddPersonaggioId.php
  db_versions/2021110109_AddMenuTable.php
  gdrcd_db.sql
  includes/required.php
  installer.php
  pages/gestione/db_migrations/gestione_db_migrations.php
  pages/gestione_db_migrations.php
  vocabulary/IT-it.vocabulary.php
Labels: enhancement

#220 GDRCD 6.0 - Esiti in chat
  classes/Controller/Abilita.class.php
  classes/Controller/Chat.class.php
  classes/Controller/Esiti.class.php
  classes/Controller/Personaggio.class.php
  classes/Libraries/DB.class.php
  classes/Libraries/Filters.class.php
  classes/Libraries/Functions.class.php
  classes/Libraries/Permissions.class.php
  config.inc.php
  core/constant_values.php
  core/db_config.php
  db_versions/2021110107_PermissionsDB.php
  gdrcd_db.sql
  pages/chat/JS/chat_dadi.js
  pages/chat/chat_ajax.php
  pages/chat/chat_input.php
  pages/chat/pannelli/esiti_chat.php
  pages/esiti/esiti_index.php
  pages/esiti/esiti_list.php
  pages/esiti/esiti_new.php
  pages/esiti/esiti_read.php
  pages/esiti_pg/new.php
  pages/gestione/esiti/JS/esiti_new.js
  pages/gestione/esiti/JS/esiti_read.js
  pages/gestione/esiti/esiti_ajax.php
  pages/gestione/esiti/esiti_close.php
  pages/gestione/esiti/esiti_index.php
  pages/gestione/esiti/esiti_list.php
  pages/gestione/esiti/esiti_master.php
  pages/gestione/esiti/esiti_members.php
  pages/gestione/esiti/esiti_new.php
  pages/gestione/esiti/esiti_open.php
  pages/gestione/esiti/esiti_read.php
  pages/gestione/segnalazioni/esiti_master.php
  pages/gestione/segnalazioni/esito_index.php
  pages/gestione/segnalazioni/new_esito/add.php
  pages/gestione/segnalazioni/new_esito/edit.php
  pages/gestione/segnalazioni/new_esito/new.php
  pages/gestione/segnalazioni/new_esito/new_chat.php
  pages/gestione_esiti.inc.php
  pages/servizi_esiti.inc.php
  pages/uffici.inc.php
  themes/advanced/chat.css
  themes/advanced/main.css
Labels: enhancement, pending, v6.0

#230 GDRCD 6.0 - Status online avanzato
  classes/Controller/OnlineStatus.class.php
  classes/Controller/Personaggio.class.php
  gdrcd_db.sql
  header.inc.php
  imgs/icons/permessi5.gif
  index.php
  pages/frame/presenti/index.inc.php
  pages/gestione/online_status/gestione_status.js
  pages/gestione/online_status/gestione_status.php
  pages/gestione/online_status/gestione_status_ajax.php
  pages/gestione/online_status/gestione_status_type.js
  pages/gestione/online_status/gestione_status_type.php
  pages/gestione/pagina_gestione_example.php
  pages/gestione_stato_online.inc.php
  pages/gestione_tipo_stato_online.inc.php
  pages/online_status/choose_status.js
  pages/online_status/choose_status.php
  pages/online_status/online_status_ajax.php
  pages/presenti_estesi.inc.php
  themes/advanced/main.css
Labels: enhancement, pending, v6.0
