Repository GDRCD/GDRCD, pull requests merged in 2021-09, with the labels that each got.

#152 Gestione Modali
  footer.inc.php
  includes/modal.js
Labels: enhancement

#128 Implementata la possibilita' di scegliere tra piu' temi diversi per g…
  config.inc.php
  includes/required.php
  login.php
  ref_header.inc.php
  themes/advanced/home/index.php
  themes/advanced/homepage.css
  themes/basic/home/index.php
  vocabulary/IT-it.vocabulary.php
Labels: enhancement, pending

#129 Prepared statements
  includes/functions.inc.php
  login.php
Labels: enhancement, pending

#158 Link Scheda su Avatar Chat
  config.inc.php
  ref_header.inc.php
Labels: enhancement

#162 Vari Fix dei Messaggi
  pages/messages/eraseall.inc.php
  pages/messages/index.inc.php
  pages/messages/send_message.inc.php
  pages/messages_center.inc.php
  themes/advanced/messaggi.css
  themes/basic/messaggi.css
Labels: fix
