Repository GDRCD/GDRCD, pull requests merged in 2022-08, with the labels that each got.

#287 GDRCD 5.6.0.6 - Hotfix dadi
  config.inc.php
  ref_header.inc.php
Labels: fix, v5.6

#289 GDRCD 6 - Php8 integration
  .gitignore
  core/classes/Libraries/Routing.class.php
  includes/default/classes/Controller/Chat/Chat.class.php
  includes/default/classes/Controller/Meteo/MeteoStagioni.class.php
  includes/default/classes/Controller/Personaggio/PersonaggioAbilita.class.php
  includes/default/pages/messages/send_message.inc.php
Labels: enhancement, v6.0

#290 GDRCD 6 - Mysqli to pdo
  core/classes/Libraries/DB.class.php
  core/classes/Libraries/DbMigrationEngine.class.php
Labels: enhancement, v6.0

#288 GDRCD 6 - Correzioni varie nella pagina delle Razze di Gioco
  includes/default/pages/homepage/user_razze.inc.php
Labels: fix, v6.0

#293 GDRCD 5.6.0.6 - Fix Homepage
  includes/credits.inc.php
  pages/homepage/iscrizione.inc.php
Labels: fix, v5.6
