Repository GDRCD/GDRCD, pull requests merged in 2022-01, with the labels that each got.

#233 Char stat
  classes/Controller/Abilita.class.php
  classes/Controller/Chat.class.php
  classes/Controller/Personaggio/Personaggio.class.php
  classes/Controller/Personaggio/PersonaggioStats.class.php
  classes/Controller/Scheda/SchedaOggetti.class.php
  classes/Controller/Scheda/SchedaStats.class.php
  classes/Controller/Statistiche.class.php
  gdrcd_db.sql
  header.inc.php
  pages/chat/chat_input.php
  pages/gestione/abilita/Requisiti/JS/gestione_requisiti.js
  pages/gestione/abilita/Requisiti/gestione_requisiti.php
  pages/gestione/statistiche/gestione_statistiche.js
  pages/gestione/statistiche/gestione_statistiche.php
  pages/gestione/statistiche/gestione_statistiche_ajax.php
  pages/gestione_statistiche.inc.php
  pages/scheda/menu.inc.php
  pages/scheda/stats/downgrade.php
  pages/scheda/stats/index.php
  pages/scheda/stats/list.php
  pages/scheda/stats/upgrade.php
  pages/scheda_px.inc.php
  pages/scheda_skill.inc.php
  pages/scheda_stats.inc.php
  plugins/FakeTable.js
  themes/advanced/main.css
  themes/advanced/scheda.css
  vocabulary/IT-it.vocabulary.php
Labels: enhancement, v6.0

#234 Abi refactor
  classes/Controller/Abilita.class.php
  classes/Controller/Abilita/Abilita.class.php
  classes/Controller/Abilita/AbilitaExtra.class.php
  classes/Controller/Abilita/AbilitaRequisiti.class.php
  classes/Controller/Chat/Chat.class.php
  classes/Controller/Chat/ChatAbilita.class.php
  classes/Controller/Personaggio/Personaggio.class.php
  classes/Controller/Personaggio/PersonaggioAbilita.class.php
  classes/Controller/Scheda/SchedaAbilita.class.php
  gdrcd_db.sql
  pages/chat/chat_input.php
  pages/gestione/abilita/Extra/gestione_abilita_ajax.php
  pages/gestione/abilita/Extra/gestione_abilita_box.php
  pages/gestione/abilita/Extra/gestione_abilita_extra.js
  pages/gestione/abilita/Extra/gestione_abilita_extra.php
  pages/gestione/abilita/Requisiti/JS/gestione_requisiti.js
  pages/gestione/abilita/Requisiti/gestione_requisiti.js
  pages/gestione/abilita/Requisiti/gestione_requisiti.php
  pages/gestione/abilita/Requisiti/gestione_requisiti_ajax.php
  pages/gestione_abilita_extra.inc.php
  pages/scheda/abilita/downgrade.php
  pages/scheda/abilita/index.php
  pages/scheda/abilita/list.php
  pages/scheda/abilita/upgrade.php
  pages/scheda/menu.inc.php
  pages/scheda_skill.inc.php
Labels: enhancement, fix, v6.0

#235 [master] GDRCD - 5.6.0.2
  .gitignore
  config.inc.php
  includes/AudioController.php
  includes/functions.inc.php
  license.md
  pages/homepage/home.inc.php
  pages/messages/create.inc.php
  pages/presenti_estesi.inc.php
  pages/scheda.inc.php
  pages/scheda_px.inc.php
  ref_header.inc.php
Labels: fix, v5.6.0.2
