Repository GDRCD/GDRCD, pull requests merged in 2022-07, with the labels that each got.

#262 GDRCD 5.6.0.4 - Aggiornamento controlli Gestione > Manutenzione
  config.inc.php
  includes/functions.inc.php
  pages/gestione/manutenzione/blacklisted.inc.php
  pages/gestione/manutenzione/deleted.inc.php
  pages/gestione/manutenzione/index.inc.php
  pages/gestione/manutenzione/missing.inc.php
  pages/gestione/manutenzione/old_chat.inc.php
  pages/gestione/manutenzione/old_log.inc.php
  pages/gestione/manutenzione/old_messages.inc.php
  pages/gestione/manutenzione/view.inc.php
  pages/gestione_manutenzione.inc.php
  vocabulary/IT-it.vocabulary.php
Labels: enhancement, fix, v5.6.x

#261 GDRCD 5.6.0.4 - DbMigration
  includes/DbMigration/DbMigration.class.php
  includes/DbMigration/DbMigrationEngine.class.php
  includes/required.php
Labels: enhancement, v5.6.x

#246 GDRCD 6.0 - Contatti
  db_versions/20220701_GDRCD6.php
  gdrcd_db.sql
  includes/default/classes/Controller/Contacts/Contatti.class.php
  includes/default/classes/Controller/Contacts/ContattiCategorie.class.php
  includes/default/classes/Controller/Contacts/ContattiNote.class.php
  includes/default/classes/Controller/Personaggio/Personaggio.class.php
  includes/default/classes/Controller/Scheda/SchedaContatti.class.php
  includes/default/pages/gestione/contatti/gestione_categorie.js
  includes/default/pages/gestione/contatti/gestione_categorie.php
  includes/default/pages/gestione/contatti/gestione_categorie_ajax.php
  includes/default/pages/scheda/contatti/JS/contact_delete.js
  includes/default/pages/scheda/contatti/JS/contact_edit.js
  includes/default/pages/scheda/contatti/JS/contact_new.js
  includes/default/pages/scheda/contatti/JS/note_edit.js
  includes/default/pages/scheda/contatti/JS/note_new.js
  includes/default/pages/scheda/contatti/JS/note_view.js
  includes/default/pages/scheda/contatti/contact_ajax.php
  includes/default/pages/scheda/contatti/contact_edit.php
  includes/default/pages/scheda/contatti/contact_new.php
  includes/default/pages/scheda/contatti/index.php
  includes/default/pages/scheda/contatti/index_popup.php
  includes/default/pages/scheda/contatti/list.php
  includes/default/pages/scheda/contatti/note_details.php
  includes/default/pages/scheda/contatti/note_edit.php
  includes/default/pages/scheda/contatti/note_new.php
  includes/default/pages/scheda/contatti/note_view.php
  includes/default/pages/scheda/menu.inc.php
  includes/default/pages/scheda_contatti.inc.php
  includes/default/pages/scheda_contatti_nota.inc.php
  includes/default/themes/main.css
  includes/default/themes/view/smarty/templates/scheda/contatti/list.tpl
  includes/default/themes/view/smarty/templates/scheda/contatti/note_list.tpl
  themes/advanced/view/smarty/templates/scheda/contatti/list.tpl
  themes/advanced/view/smarty/templates/scheda/contatti/note_list.tpl
  vocabulary/IT-it.vocabulary.php
Labels: enhancement, pending, v6.0

#269 GDRCD 5.6.0.4 [EMAIL]
  config.inc.php
  pages/gestione_cambio_email.inc.php
  pages/scheda_gst.inc.php
  vocabulary/IT-it.vocabulary.php
Labels: bug, fix, v5.6.x

#270 GDRCD 6 - Reset fix
  config.inc.php
  core/classes/Libraries/DB.class.php
  core/classes/Libraries/DbMigrationEngine.class.php
  core/classes/Libraries/Functions.class.php
  reset.php
Labels: fix, v6.0

#266 GDRCD 6.0 - Chat Customizations
  core/classes/Libraries/Filters.class.php
  core/functions.php
  db_versions/20220701_GDRCD6.php
  gdrcd_db.sql
  includes/default/classes/Controller/Chat/Chat.class.php
  includes/default/classes/Controller/Chat/ChatOpzioni.class.php
  includes/default/classes/Controller/Gestione.class.php
  includes/default/classes/Controller/Personaggio/PersonaggioChatOpzioni.class.php
  includes/default/classes/Controller/Scheda/SchedaChatOpzioni.class.php
  includes/default/pages/gestione/chat/opzioni/gestione_chat_opzioni.js
  includes/default/pages/gestione/chat/opzioni/gestione_chat_opzioni.php
  includes/default/pages/gestione/chat/opzioni/gestione_chat_opzioni_ajax.php
  includes/default/pages/scheda/chat/opzioni/ajax.php
  includes/default/pages/scheda/chat/opzioni/index.php
  includes/default/pages/scheda/chat/opzioni/update.php
  includes/default/pages/scheda/menu.inc.php
  includes/default/themes/chat.css
  vocabulary/IT-it.vocabulary.php
Labels: enhancement, v6.0

#271 GDRCD 5.6.0.4 - Revisione Presentazione in Homepage
  pages/homepage/home.inc.php
Labels: enhancement, v5.6.x

#275 GDRCD 5.6.0.4 - Forum Permessi
  includes/functions.inc.php
  pages/forum/edit.inc.php
  pages/forum/insert.inc.php
  pages/forum/list.inc.php
  pages/forum/read.inc.php
  pages/forum/visit.inc.php
Labels: fix, v5.6.x

#277 GDRCD 5.6.0.4 - Backtrace migliorato
  includes/functions.inc.php
  themes/advanced/main.css
  themes/homepage/advanced/homepage.css
Labels: fix, v5.6.x

#273 [master] GDRCD - 5.6.0.4
  config.inc.php
  includes/DbMigration/DbMigration.class.php
  includes/DbMigration/DbMigrationEngine.class.php
  includes/functions.inc.php
  includes/required.php
  layouts/bottom_frames.php
  layouts/left-bottom_frames.php
  layouts/left-right-bottom_frames.php
  layouts/left-right_frames.php
  layouts/left-top-bottom_frames.php
  layouts/left-top-right-bottom_frames.php
  layouts/left-top-right_frames.php
  layouts/left-top_frames.php
  layouts/left_frames.php
  layouts/right_frames.php
  layouts/top-bottom_frames.php
  layouts/top_frames.php
  license.md
  login.php
  main.php
  pages/forum.inc.php
  pages/forum/edit.inc.php
  pages/forum/index.inc.php
  pages/forum/insert.inc.php
  pages/forum/list.inc.php
  pages/forum/read.inc.php
  pages/forum/visit.inc.php
  pages/gestione/manutenzione/blacklisted.inc.php
  pages/gestione/manutenzione/deleted.inc.php
  pages/gestione/manutenzione/index.inc.php
  pages/gestione/manutenzione/missing.inc.php
  pages/gestione/manutenzione/old_chat.inc.php
  pages/gestione/manutenzione/old_log.inc.php
  pages/gestione/manutenzione/old_messages.inc.php
  pages/gestione/manutenzione/view.inc.php
  pages/gestione/segnalazioni/esiti_master.php
  pages/gestione/segnalazioni/new_esito/insert.php
  pages/gestione/segnalazioni/new_esito/new.php
  pages/gestione/segnalazioni/new_esito/new_chat.php
  pages/gestione/segnalazioni/roles_gm.php
  pages/gestione_cambio_email.inc.php
  pages/gestione_manutenzione.inc.php
  pages/homepage/home.inc.php
  pages/scheda/roles/edit.inc.php
  pages/scheda/roles/index.inc.php
  pages/scheda/roles/log.inc.php
  pages/scheda/roles/register.inc.php
  pages/scheda/roles/search.inc.php
  pages/scheda/roles/segnala.inc.php
  pages/scheda_gst.inc.php
  pages/servizi/prenotazioni/index.inc.php
  ref_header.inc.php
  themes/advanced/main.css
  themes/homepage/advanced/homepage.css
  vocabulary/IT-it.vocabulary.php
Labels: v5.6.x, release

#258 GDRCD 6 - Corp v2
  core/classes/Libraries/Cronjob.class.php
  core/classes/Libraries/Routing.class.php
  core/classes/Libraries/Wrapper/CarbonWrapper.class.php
  db_versions/20220701_GDRCD6.php
  gdrcd_db.sql
  includes/default/classes/Controller/Chat/Chat.class.php
  includes/default/classes/Controller/Gruppi/Gruppi.class.php
  includes/default/classes/Controller/Gruppi/GruppiFondi.class.php
  includes/default/classes/Controller/Gruppi/GruppiOggetto.class.php
  includes/default/classes/Controller/Gruppi/GruppiRuoli.class.php
  includes/default/classes/Controller/Gruppi/GruppiStipendiExtra.class.php
  includes/default/classes/Controller/Personaggio/PersonaggioChatOpzioni.class.php
  includes/default/classes/Controller/Personaggio/PersonaggioRuolo.class.php
  includes/default/pages/chat/JS/chat_input.js
  includes/default/pages/chat/chat_input.php
  includes/default/pages/gestione/gruppi/fondi/gestione_fondi.js
  includes/default/pages/gestione/gruppi/fondi/gestione_fondi.php
  includes/default/pages/gestione/gruppi/fondi/gestione_fondi_ajax.php
  includes/default/pages/gestione/gruppi/gruppi/gestione_gruppi.js
  includes/default/pages/gestione/gruppi/gruppi/gestione_gruppi.php
  includes/default/pages/gestione/gruppi/stipendiExtra/gestione_stipendi_extra.js
  includes/default/pages/gestione/gruppi/stipendiExtra/gestione_stipendi_extra.php
  includes/default/pages/gestione/gruppi/stipendiExtra/gestione_stipendi_extra_ajax.php
  includes/default/pages/servizi/amministrazioneGilde/ajax.php
  includes/default/pages/servizi/amministrazioneGilde/index.php
  includes/default/pages/servizi/amministrazioneGilde/view.php
  includes/default/pages/servizi/amministrazioneGilde/view_extra_earn.js
  includes/default/pages/servizi/amministrazioneGilde/view_extra_earn.php
  includes/default/pages/servizi/gruppi/ajax.php
  includes/default/pages/servizi/gruppi/storage.js
  includes/default/pages/servizi/gruppi/storage.php
  includes/default/themes/main.css
  includes/default/themes/view/smarty/templates/oggetti/storage-objects.tpl
  includes/default/themes/view/smarty/templates/oggetti/storage-single-object.tpl
  includes/default/themes/view/smarty/templates/servizi/gruppi_list.tpl
  plugins/Ajax.js
Labels: enhancement, v6.0

#281 GDRCD 6 - Presenti Refactor
  config.inc.php
  db_versions/20220701_GDRCD6.php
  header.inc.php
  includes/default/classes/Controller/Gruppi/GruppiOggetto.class.php
  includes/default/classes/Controller/Presenti.class.php
  includes/default/pages/presenti/ajax.php
  includes/default/pages/presenti/full.php
  includes/default/pages/presenti/mini.js
  includes/default/pages/presenti/mini.php
  includes/default/themes/presenti.css
  includes/default/themes/view/smarty/templates/presenti/full.tpl
  includes/default/themes/view/smarty/templates/presenti/mini.tpl
Labels: enhancement, v6.0

#283 GDRCD 6 - Log v1
  db_versions/20220701_GDRCD6.php
  gdrcd_db.sql
  includes/default/classes/Controller/Log.class.php
  includes/default/classes/Controller/Quest.class.php
  includes/default/pages/scheda_px.inc.php
  login.php
Labels: enhancement, v6.0

#280 GDRCD 5.6.0.5 - Minor fix
  config.inc.php
  includes/functions.inc.php
  pages/gestione/segnalazioni/esiti_master.php
  pages/gestione/segnalazioni/roles_gm.php
  pages/servizi_esiti.inc.php
Labels: fix, v5.6.x

#279 GDRCD 5.6.0.5 - Release
  config.inc.php
  includes/functions.inc.php
  pages/esiti_pg/first.php
  pages/gestione/segnalazioni/esiti_master.php
  pages/gestione/segnalazioni/new_esito/add.php
  pages/gestione/segnalazioni/new_esito/edit.php
  pages/gestione/segnalazioni/new_esito/first.php
  pages/gestione/segnalazioni/new_esito/insert.php
  pages/gestione/segnalazioni/new_esito/modify.php
  pages/gestione/segnalazioni/new_esito/new.php
  pages/gestione/segnalazioni/roles_gm.php
  pages/gestione_luoghi.inc.php
  pages/homepage/reset_password.inc.php
  pages/messages/send_message.inc.php
  pages/presenti_estesi.inc.php
  pages/scheda.inc.php
  pages/scheda/roles/send_reg.inc.php
  pages/scheda/skillsystem.inc.php
  pages/servizi_esiti.inc.php
  ref_header.inc.php
Labels: v5.6, release
