Repository GDRCD/GDRCD, pull requests merged in 2022-09, with the labels that each got.

#292 GDRCD 6 - Login
  core/classes/Libraries/Base.class.php
  core/classes/Libraries/Crypter/CrypterAlgo.class.php
  core/classes/Libraries/Crypter/CrypterPasswordArgon2.class.php
  core/classes/Libraries/Crypter/CrypterPasswordBlowfish.class.php
  core/classes/Libraries/Crypter/CrypterPasswordSha256.class.php
  core/classes/Libraries/Crypter/CrypterPasswordSha512.class.php
  core/classes/Libraries/DB.class.php
  core/classes/Libraries/Functions.class.php
  core/classes/Libraries/Login.class.php
  core/classes/Libraries/Password.class.php
  core/classes/Libraries/Session.class.php
  core/classes/Libraries/Wrapper/CarbonWrapper.class.php
  core/required.php
  db_versions/20220701_GDRCD6.php
  includes/default/pages/homepage/index.inc.php
  includes/default/pages/user_cambio_pass.inc.php
  includes/default/themes/view/smarty/templates/login-error.tpl
  login.php
  logout.php
  protezione.php
  vocabulary/IT-it.vocabulary.php
Labels: enhancement, fix, v6.0

#299 GDRCD 6 - Ripristinato un controllo in Login.class.php andato perso col refactoring. La classe Login è stata inoltre spostata nei controllers
  includes/default/classes/Controller/Login.class.php
Labels: fix, v6.0

#302 GDRCD 6 - Banca
  db_versions/20220701_GDRCD6.php
  includes/default/classes/Controller/Personaggio/Personaggio.class.php
  includes/default/classes/Controller/Servizi/Banca.class.php
  includes/default/pages/servizi/banca/ajax.php
  includes/default/pages/servizi/banca/index.js
  includes/default/pages/servizi/banca/index.php
Labels: enhancement, v6.0
