Repository GDRCD/GDRCD, pull requests merged in 2025-08, with the labels that each got.

#370 [v5.7] - Refactor sezione Log Chat
  pages/gestione/log_chat/index.inc.php
  pages/gestione/log_chat/save.inc.php
  pages/log_chat.inc.php
Labels: enhancement

#382 [v5.7] - Rimuove cartella `docs`
  README.md
  docs/.gitkeep
Labels: enhancement, v5.7

#348 [v5.7] - Refactor ref_header.inc.php e chat
  .gitignore
  ajax.php
  config.inc.php
  db_versions/2025073023_GDRCD57.php
  includes/AudioController.class.php
  includes/constant_values.inc.php
  includes/functions.api.inc.php
  includes/functions.chat_core.inc.php
  includes/functions.chat_read.inc.php
  includes/functions.chat_write.inc.php
  includes/functions.inc.php
  includes/jquery-3.7.1.min.js
  includes/required.php
  main.php
  pages/blocco_note.inc.php
  pages/chat.inc.php
  pages/chat/ajax.inc.php
  pages/chat/chat_box.php
  pages/chat/chat_input.php
  pages/chat/op/read.inc.php
  pages/chat/op/skillsystem.inc.php
  pages/chat/op/write.inc.php
  pages/chat_pannelli_index.inc.php
  pages/frame_chat.inc.php
  pages/presenti.inc.php
  ref_header.inc.php
  themes/advanced/chat.css
  themes/advanced/imgs/chat-loading.gif
  vocabulary/IT-it.vocabulary.php
Labels: enhancement, v5.7

#386 [v5.7] - Fix engine migrazioni e nuova convenzione nomi
  db_versions/2025073023_GDRCD57_Convert_Chat_To_Utf8mb4.php
  includes/DbMigration/DbMigration.class.php
  includes/DbMigration/DbMigrationEngine.class.php
Labels: enhancement, fix, v5.7
